# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_orig', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('surname_orig', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_orig', models.CharField(max_length=255)),
                ('teaser', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('isbn', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('authors', models.ManyToManyField(to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_orig', models.CharField(max_length=255)),
                ('teaser', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(to='books.Series'),
        ),
    ]
