# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170123_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='series',
        ),
        migrations.AddField(
            model_name='author',
            name='series',
            field=models.ManyToManyField(blank=True, to='books.Series'),
        ),
    ]
