# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170123_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='author',
            name='series',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Series'),
        ),
    ]
