# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170125_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/default.jpg', upload_to='authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default.jpg', upload_to='books'),
        ),
    ]
