# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170515_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default.jpeg', upload_to='books'),
        ),
    ]
