# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170517_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/media/books/default.jpeg', upload_to='books'),
        ),
    ]
