# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170703_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('ru', 'Русский'), ('en', 'English'), ('pl', 'Polish')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Translator'),
        ),
    ]
