# Generated by Django 2.0.7 on 2018-07-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170703_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('de', 'German'), ('pl', 'Polish'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
