# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20170125_1026'),
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together=set([('user', 'book', 'action')]),
        ),
    ]
