# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20170629_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='action',
            field=models.CharField(choices=[('want-to-read', 'Want to read'), ('like', 'Like'), ('currently-reading', 'Currently reading'), ('read', 'Read'), ('have', 'Have')], max_length=200),
        ),
    ]
