# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20170703_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='action',
            field=models.CharField(choices=[('want-to-read', 'Want to read'), ('have', 'Have'), ('like', 'Like'), ('read', 'Read'), ('currently-reading', 'Currently reading')], max_length=200),
        ),
    ]
