# Generated by Django 2.0.7 on 2018-07-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20170703_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='action',
            field=models.CharField(choices=[('want-to-read', 'Want to read'), ('currently-reading', 'Currently reading'), ('read', 'Read'), ('like', 'Like'), ('have', 'Have')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
